<?php

/** @var \Mavenbird\Blog\Block\Rss\Widget $block */
?>
<div class="mbblog-sidebar-block mbblog-rss-widget">
    <div class="block-content">
        <a class="mbblog-rss-link"
            href="<?= $block->escapeUrl($block->getRssUrl()) ?>"
            target="_blank"
            rel="noopener">

            <img src="<?= $block->escapeUrl(
                            $block->getViewFileUrl('Mavenbird_Blog::media/images/rss.png')
                        ) ?>"
                alt="<?= $block->escapeHtmlAttr(__('RSS Feed')) ?>"
                width="18"
                height="18" />
        </a>
    </div>
</div>